/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Panos
 */

import radiostation.RadioStation;

public class MainMenu extends javax.swing.JFrame {
    private RadioStation rs = new RadioStation();

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        this.rs = new RadioStation();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuArtist = new javax.swing.JMenuItem();
        menuGroup = new javax.swing.JMenuItem();
        menuGroupAlbum = new javax.swing.JMenuItem();
        menuArtistAlbum = new javax.swing.JMenuItem();
        MenuPlaylists = new javax.swing.JMenu();
        MenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));

        jLabel1.setFont(new java.awt.Font("Nanum Brush Script", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RadioStation");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel2.setText("Developed by: Eleni Stamatiadou, Giorgos Tampakis, Panagiotis Trililos & Elias Tsourapas");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setText("ΕΑΠ | ΠΛΗ24 2014-2015");

        jMenu1.setText("Διαχείριση αρχείων");

        menuArtist.setText("Καλλιτέχνες");
        menuArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArtistActionPerformed(evt);
            }
        });
        jMenu1.add(menuArtist);

        menuGroup.setText("Συγκροτήματα");
        menuGroup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGroupActionPerformed(evt);
            }
        });
        jMenu1.add(menuGroup);

        menuGroupAlbum.setText("Άλμπουμ Συγκροτημάτων");
        menuGroupAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuGroupAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGroupAlbumActionPerformed(evt);
            }
        });
        jMenu1.add(menuGroupAlbum);

        menuArtistAlbum.setText("Άλμπουμ Καλλιτεχνών");
        menuArtistAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArtistAlbumActionPerformed(evt);
            }
        });
        jMenu1.add(menuArtistAlbum);

        jMenuBar1.add(jMenu1);

        MenuPlaylists.setText("Λίστες τραγουδιών");
        MenuPlaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPlaylistsActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuPlaylists);

        MenuExit.setText("Έξοδος");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArtistActionPerformed
        // TODO add your handling code here:
        R2_ArtistList_View alv = new R2_ArtistList_View();
        alv.setVisible(true);
    }//GEN-LAST:event_menuArtistActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPlaylistsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPlaylistsActionPerformed

    private void menuGroupAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGroupAlbumActionPerformed
        // TODO add your handling code here:
        R8_GroupAlbum_View gav = new R8_GroupAlbum_View();
        gav.setVisible(true);
    }//GEN-LAST:event_menuGroupAlbumActionPerformed

    private void menuGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGroupActionPerformed
        // TODO add your handling code here:
        R4_GroupList_View glv = new R4_GroupList_View();
        glv.setVisible(true);
    }//GEN-LAST:event_menuGroupActionPerformed

    private void menuArtistAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArtistAlbumActionPerformed
        // TODO add your handling code here:
        R12_ArtistAlbum_View aav = new R12_ArtistAlbum_View();
        aav.setVisible(true);
    }//GEN-LAST:event_menuArtistAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuExit;
    private javax.swing.JMenu MenuPlaylists;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuArtist;
    private javax.swing.JMenuItem menuArtistAlbum;
    private javax.swing.JMenuItem menuGroup;
    private javax.swing.JMenuItem menuGroupAlbum;
    // End of variables declaration//GEN-END:variables
}
