
/*ΜΗΝ ΤΟΝ ΤΡΕΞΕΤΕ ΑΚΟΜΑ ΤΟΝ ΚΩΔΙΚΑ!!!*/
/*ΜΗΝ ΤΟΝ ΤΡΕΞΕΤΕ ΑΚΟΜΑ ΤΟΝ ΚΩΔΙΚΑ!!!*/
/*ΜΗΝ ΤΟΝ ΤΡΕΞΕΤΕ ΑΚΟΜΑ ΤΟΝ ΚΩΔΙΚΑ!!!*/

/*Αλλαγή των PK και FK αναφορικά με τους πίνακες Συγκροτημάτων και Εταιρειών Παραγωγής*/

/*Διαγραφή του κάθε FK από τους πίνακες όπου υπάρχει*/
ALTER TABLE ALBUM
    DROP CONSTRAINT MUSICGROUP_FK;

ALTER TABLE ALBUM
    DROP CONSTRAINT MUSICPRODUCTIONCOMPANY_FK;

ALTER TABLE MUSICGROUP_ARTISTS
    DROP CONSTRAINT ARTIST_FK;

ALTER TABLE MUSICGROUP_ARTISTS
    DROP CONSTRAINT MUSICGROUP_FK;

/*Διαγραφή πίνακα FKs που συνδέει τους πίνακες ALBUM και ARTISTS*/
DROP TABLE MUSICGROUP_ARTISTS;

/*Επαναδημιουργία του πίνακα με νέο όνομα στήλης (αντί για ID τώρα γράφει NAME)*/
CREATE TABLE MUSICGROUP_ARTISTS (
    ARTIST_ID BIGINT NOT NULL,
    MUSICGROUP_NAME BIGINT NOT NULL,
    PRIMARY KEY (ARTIST_ID, MUSICGROUP_NAME)
);

/*Προσθήκη FKs στον πίνακα*/
ALTER TABLE MUSICGROUP_ARTISTS
    ADD CONSTRAINT ARTIST_FK FOREIGN KEY (ARTIST_ID)
    REFERENCES ARTIST(ARTIST_ID);

ALTER TABLE MUSICGROUP_ARTISTS
    ADD CONSTRAINT MUSICGROUP_FK FOREIGN KEY (MUSICGROUP_NAME)
    REFERENCES MUSICGROUP(MUSICGROUP_NAME);

/*Κατάργηση PK και προσθήκη νέου στους πίνακες MUSICGROUP και MUSICPRODUCTIONCOMPANY*/
ALTER TABLE MUSICGROUP
    DROP PRIMARY KEY;

ALTER TABLE MUSICGROUP
    ADD PRIMARY KEY (MUSICGROUP_NAME);

ALTER TABLE MUSICPRODUCTIONCOMPANY
    DROP PRIMARY KEY;

ALTER TABLE MUSICPRODUCTIONCOMPANY
    ADD PRIMARY KEY (MPC_NAME);

/*Σύνδεση των νέων FKs με τον πίνακα ALBUM*/
ALTER TABLE ALBUM
    ADD CONSTRAINT MUSICPRODUCTIONCOMPANY_FK FOREIGN KEY (MPC_NAME)
            REFERENCES MUSICPRODUCTIONCOMPANY(MPC_NAME);

ALTER TABLE ALBUM
    ADD CONSTRAINT ALBUM_MUSICGROUP_FK FOREIGN KEY (MUSICGROUP_NAME)
            REFERENCES MUSICGROUP(MUSICGROUP_NAME);